server.port=8084

# ======================
# RabbitMQ
# ======================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ======================
# MAIL (SMTP Gmail)
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=dthn2004@gmail.com
spring.mail.password=bkmxqlnghgfesech
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.enable=false

# ======================
# JACKSON
# ======================
spring.jackson.serialization.write-dates-as-timestamps=false
