# ======================
# SERVER PORT
# ======================
server.port=8082

# ======================
# DATABASE
# ======================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://db:3306/online_learning}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.mariadb.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=${SPRING_JPA_DIALECT:org.hibernate.dialect.MariaDBDialect}
spring.jpa.properties.hibernate.globally_quoted_identifiers=true


# ======================
# REDIS
# ======================
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL_ENABLED:false}
spring.data.redis.timeout=2000


# ======================
# CACHE
# ======================
spring.cache.type=none


# ======================
# JACKSON (Java 8 Date/Time)
# ======================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.write-durations-as-timestamps=false


# ======================
# MAIL (SMTP Gmail)
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=dthn2004@gmail.com
spring.mail.password=bkmxqlnghgfesech

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.enable=false


# ======================
# AWS S3 & CloudFront (Fallback for local development)
# ======================
AWS_ACCESS_KEY=local
AWS_SECRET_KEY=local
AWS_REGION=us-east-1
AWS_BUCKET_NAME=local-bucket