server.port=8083

# ======================
# DATABASE (MariaDB)
# ======================
spring.datasource.url=jdbc:mariadb://db:3306/online_learning
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# ======================
# REDIS
# ======================
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=2000

# ======================
# CACHE
# ======================
spring.cache.type=none

# ======================
# JACKSON (Java 8 Date/Time)
# ======================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.write-durations-as-timestamps=false

# ======================
# RABBITMQ
# ======================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ======================
# VNPAY
# ======================
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.tmnCode=10XO0MH4
vnpay.hashSecret=UF4MIT9EMKDELUME7143CAMDU97589ND
vnpay.returnUrl=http://192.168.1.141:8083/api/v1/vnpay-callback
vnpay.bankCode=
